version: "3.9"

services:
  travel-planner:
    image: ghcr.io/sakiyary/ai4se-travel-planner:latest
    pull_policy: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped
