name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  quality:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: https://placeholder.supabase.co
      SUPABASE_ANON_KEY: public-anon-key
      SUPABASE_VOICE_BUCKET: voice-notes
      SUPABASE_EXPORT_BUCKET: plan-exports
      AMAP_WEB_KEY: dev-amap-key
      AMAP_SECURITY_JS_CODE: dev-amap-safe
      IFLYTEK_APP_ID: demo-app-id
      IFLYTEK_API_KEY: demo-api-key
      IFLYTEK_API_SECRET: demo-api-secret
      DASHSCOPE_API_KEY: demo-dashscope-key
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run typecheck

      - name: Build
        run: npm run build

      - name: Upload Next.js build artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: |
            .next
            public
            package.json
            package-lock.json
            next.config.mjs
            Dockerfile

  docker:
    needs: quality
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/sakiyary/ai4se-travel-planner:${{ github.sha }}
            ghcr.io/sakiyary/ai4se-travel-planner:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
